// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAePoFVDcK5h7pV6Y_esx4que_DQpOyuWg',
    appId: '1:362023882922:web:c959729c3d05d70ad600d3',
    messagingSenderId: '362023882922',
    projectId: 'login-auth-9aa99',
    authDomain: 'login-auth-9aa99.firebaseapp.com',
    storageBucket: 'login-auth-9aa99.firebasestorage.app',
    measurementId: 'G-JXENVBJQWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA2qtbebvLBkT0-CN0L1nbM1aSEsRHVC8',
    appId: '1:362023882922:android:ba4becb2219cfcc8d600d3',
    messagingSenderId: '362023882922',
    projectId: 'login-auth-9aa99',
    storageBucket: 'login-auth-9aa99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnZR3TFvVuFo5zKurzaODwWjatFIaSZeE',
    appId: '1:362023882922:ios:2858d0611e858c0cd600d3',
    messagingSenderId: '362023882922',
    projectId: 'login-auth-9aa99',
    storageBucket: 'login-auth-9aa99.firebasestorage.app',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnZR3TFvVuFo5zKurzaODwWjatFIaSZeE',
    appId: '1:362023882922:ios:2858d0611e858c0cd600d3',
    messagingSenderId: '362023882922',
    projectId: 'login-auth-9aa99',
    storageBucket: 'login-auth-9aa99.firebasestorage.app',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAePoFVDcK5h7pV6Y_esx4que_DQpOyuWg',
    appId: '1:362023882922:web:4fbabdd6e2278599d600d3',
    messagingSenderId: '362023882922',
    projectId: 'login-auth-9aa99',
    authDomain: 'login-auth-9aa99.firebaseapp.com',
    storageBucket: 'login-auth-9aa99.firebasestorage.app',
    measurementId: 'G-ZY81TY75D2',
  );
}
